import 'package:flutter/foundation.dart';
import 'package:ordo/core/ai/models/ai_task_parse_result.dart';
import 'package:ordo/core/ai/models/efficiency_stats.dart';

/// Type of message in AI Copilot dialogue.
enum AiChatMessageType {
  /// Message sent by the human user.
  user,

  /// Plain text message replied by the AI assistant.
  assistantText,

  /// Interactive task proposal generated by AI parser.
  taskProposal,

  /// Visual efficiency review and diagnostic report.
  efficiencyReport,
}

/// In-memory chat message state for AI Copilot.
@immutable
class AiChatMessage {
  const AiChatMessage({
    required this.id,
    required this.type,
    this.content = '',
    this.proposal,
    this.efficiencyStats,
    this.selectedSubstepIndices = const {},
    this.isPersisted = false,
    this.isPersisting = false,
    this.isDiscarded = false,
    this.isLoading = false,
    required this.createdAt,
  });

  /// Factory to construct user text message.
  factory AiChatMessage.user({
    required String id,
    required String text,
    DateTime? createdAt,
  }) {
    return AiChatMessage(
      id: id,
      type: AiChatMessageType.user,
      content: text,
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  /// Factory to construct assistant text message.
  factory AiChatMessage.assistantText({
    required String id,
    required String text,
    DateTime? createdAt,
  }) {
    return AiChatMessage(
      id: id,
      type: AiChatMessageType.assistantText,
      content: text,
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  /// Factory to construct assistant task proposal card message.
  factory AiChatMessage.taskProposal({
    required String id,
    required AiTaskParseResult proposal,
    DateTime? createdAt,
  }) {
    final allIndices = List.generate(
      proposal.substeps.length,
      (index) => index,
    ).toSet();

    return AiChatMessage(
      id: id,
      type: AiChatMessageType.taskProposal,
      content: proposal.title,
      proposal: proposal,
      selectedSubstepIndices: allIndices,
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  /// Factory to construct efficiency report message.
  factory AiChatMessage.efficiencyReport({
    required String id,
    required EfficiencyStats stats,
    String? analysisMarkdown,
    bool isLoading = false,
    DateTime? createdAt,
  }) {
    return AiChatMessage(
      id: id,
      type: AiChatMessageType.efficiencyReport,
      content: analysisMarkdown ?? '',
      efficiencyStats: stats,
      isLoading: isLoading,
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  /// Unique message ID (e.g. UUID v4).
  final String id;

  /// Message type (user, assistantText, taskProposal, efficiencyReport).
  final AiChatMessageType type;

  /// Text content or prompt preview.
  final String content;

  /// Parsed task proposal data, non-null if [type] is [AiChatMessageType.taskProposal].
  final AiTaskParseResult? proposal;

  /// Efficiency statistics, non-null if [type] is [AiChatMessageType.efficiencyReport].
  final EfficiencyStats? efficiencyStats;

  /// Indices of selected substeps that user confirmed to persist.
  final Set<int> selectedSubstepIndices;

  /// Whether this task proposal has already been persisted to local database.
  final bool isPersisted;

  /// Whether persistence request is currently in flight.
  final bool isPersisting;

  /// Whether user discarded this proposal.
  final bool isDiscarded;

  /// Whether diagnosis analysis is generating/loading.
  final bool isLoading;

  /// Message timestamp.
  final DateTime createdAt;

  AiChatMessage copyWith({
    String? id,
    AiChatMessageType? type,
    String? content,
    AiTaskParseResult? proposal,
    EfficiencyStats? efficiencyStats,
    Set<int>? selectedSubstepIndices,
    bool? isPersisted,
    bool? isPersisting,
    bool? isDiscarded,
    bool? isLoading,
    DateTime? createdAt,
  }) {
    return AiChatMessage(
      id: id ?? this.id,
      type: type ?? this.type,
      content: content ?? this.content,
      proposal: proposal ?? this.proposal,
      efficiencyStats: efficiencyStats ?? this.efficiencyStats,
      selectedSubstepIndices:
          selectedSubstepIndices ?? this.selectedSubstepIndices,
      isPersisted: isPersisted ?? this.isPersisted,
      isPersisting: isPersisting ?? this.isPersisting,
      isDiscarded: isDiscarded ?? this.isDiscarded,
      isLoading: isLoading ?? this.isLoading,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          content == other.content &&
          proposal == other.proposal &&
          efficiencyStats == other.efficiencyStats &&
          setEquals(selectedSubstepIndices, other.selectedSubstepIndices) &&
          isPersisted == other.isPersisted &&
          isPersisting == other.isPersisting &&
          isDiscarded == other.isDiscarded &&
          isLoading == other.isLoading &&
          createdAt == other.createdAt;

  @override
  int get hashCode => Object.hash(
    id,
    type,
    content,
    proposal,
    efficiencyStats,
    Object.hashAll(selectedSubstepIndices),
    isPersisted,
    isPersisting,
    isDiscarded,
    isLoading,
    createdAt,
  );
}
